services:
  mysql:
    image: 'mysql:9.1.0'
    environment:
      - 'MYSQL_DATABASE=sales'
      - 'MYSQL_PASSWORD=rotini'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=rotini'
    ports:
      - '3306:3306'
